#!/bin/bash

OUTDIR=output

cd ../../../er_build/
make -j4
cd -

echo -e "\e[1m\e[32m========== Compilation finished =========== \e[0m"

cd ${OUTDIR}
rm -fv *
cd -

echo -e "\e[1m\e[32m========== Cleanup finished =============== \e[0m"

root -l -b -q "sim.C(1000000, 0)" > ${OUTDIR}/out.txt 2> ${OUTDIR}/err.txt

echo -e "\e[1m\e[32m========== Simulation finished ============ \e[0m"
